# REGISTRAR ECOAPRENDIZ
POST http://127.0.0.1:5000/usuario_routes/registro_ecoaprendiz
Content-Type: application/json

{
    "email": "semivaldi@gmail.com",
    "contrasena": "123456",
    "fec_nac": "2002-06-11",
    "username": "eucalipto"
}
###

# INICIAR SESION ECOAPRENDIZ
POST http://127.0.0.1:5000/usuario_routes/login_ecoaprendiz
Content-Type: application/json

{
    "email": "semivaldi@gmail.com",
    "contrasena": "123456"
}
###

# VERIFICAN EMAIL
POST http://127.0.0.1:5000/usuario_routes/verificar_email
Content-Type: application/json

{
    "email": "semivaldi@gmail.com"
}
###

# VERIFICAR USERNAME
POST http://127.0.0.1:5000/usuario_routes/verificar_username
Content-Type: application/json

{
    "username": "eucalipto"
}
###