# REGISTRAR ECOAPRENDIZ
POST http://127.0.0.1:5000/usuario_routes/registro_ecoaprendiz
Content-Type: application/json

{
    "email": "isaproyectosfisi@gmail.com",
    "contrasena": "123456",
    "fec_nac": "2002-06-11",
    "username": "banano"
}
###

# INICIAR SESION ECOAPRENDIZ
POST http://127.0.0.1:5000/usuario_routes/login_ecoaprendiz
Content-Type: application/json

{
    "email": "isaproyectosfisi@gmail.com",
    "contrasena": "123456"
}
###

# VERIFICAN EMAIL
POST http://127.0.0.1:5000/usuario_routes/verificar_email
Content-Type: application/json

{
    "email": "semivaldi@gmail.com"
}
###

# VERIFICAR USERNAME
POST http://127.0.0.1:5000/usuario_routes/verificar_username
Content-Type: application/json

{
    "username": "eucalipto"
}
###

# OBTENER VENDEDOR POR ID
POST http://127.0.0.1:5000/usuario_routes/obtener_username_vendedor
Content-Type: application/json

{
    "id_usuario": 2
}
###